apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: quiz
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: quizapp-rds
  - extract:
      key: quizapp-jwt