version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: quiz-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped
  backend:
    build:
      context: ./QuizAppBackend
      dockerfile: Dockerfile
    image: bindasp/quiz-backend:latest
    container_name: quiz-backend
    ports:
      - "5000:5000"
    env_file:
      - QuizAppBackend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./Quiz-page-Based
      dockerfile: Dockerfile
    image: bindasp/quiz-frontend:latest
    container_name: quiz-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: quiz-net

volumes:
  pgdata: {}
