apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-frontend-nginx
  namespace: quiz
data:
  nginx.conf: |
    events {}
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;

      server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
          try_files $uri $uri/ /index.html;
        }

        location = /config.json {
          try_files $uri =404;
        }

        location /api/ {
          proxy_pass http://backend:5000/;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
