apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: quiz-secretstore
  namespace: quiz
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key